spring.application.name=Training_system

# ================= DATABASE =================
spring.datasource.url=jdbc:mysql://localhost:3306/training_db
spring.datasource.username=root
spring.datasource.password=sahil

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ================= SERVER =================
server.port=8080

# ================= TWILIO =================
twilio.sid=AC455e472d4ef30a89237fcbff62054d81
twilio.token=dc11e6ac84f9ce6967ff5052cacf45ee
twilio.whatsapp.from=whatsapp:+14155238886

# \u2705 ADD THIS (VERY IMPORTANT FOR SMS)
twilio.sms.from=+1XXXXXXXXXX

app.admin.phone=+917798031294

# ================= FILE UPLOAD =================
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

file.upload-dir=uploads/

# ================= OPTIONAL =================
app.base-url=http://localhost:8080